spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: postgres
    password: 123456

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug
