spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.mysql: debug
